import { ChordVoicing, GuitarStringNote, TuningPreset } from "../types";

export const DROP_C_STRINGS: GuitarStringNote[] = [
  { stringNumber: 6, name: "C2", note: "C", octave: 2, targetFreq: 65.41 },
  { stringNumber: 5, name: "G2", note: "G", octave: 2, targetFreq: 98.0 },
  { stringNumber: 4, name: "C3", note: "C", octave: 3, targetFreq: 130.81 },
  { stringNumber: 3, name: "F3", note: "F", octave: 3, targetFreq: 174.61 },
  { stringNumber: 2, name: "A3", note: "A", octave: 3, targetFreq: 220.0 },
  { stringNumber: 1, name: "D4", note: "D", octave: 4, targetFreq: 293.66 },
];

export const TUNING_PRESETS_MAP: Record<TuningPreset, GuitarStringNote[]> = {
  "Drop C (C-G-C-F-A-D)": DROP_C_STRINGS,
  "Drop D (D-A-D-G-B-E)": [
    { stringNumber: 6, name: "D2", note: "D", octave: 2, targetFreq: 73.42 },
    { stringNumber: 5, name: "A2", note: "A", octave: 2, targetFreq: 110.0 },
    { stringNumber: 4, name: "D3", note: "D", octave: 3, targetFreq: 146.83 },
    { stringNumber: 3, name: "G3", note: "G", octave: 3, targetFreq: 196.0 },
    { stringNumber: 2, name: "B3", note: "B", octave: 3, targetFreq: 246.94 },
    { stringNumber: 1, name: "E4", note: "E", octave: 4, targetFreq: 329.63 },
  ],
  "D Standard (D-G-C-F-A-D)": [
    { stringNumber: 6, name: "D2", note: "D", octave: 2, targetFreq: 73.42 },
    { stringNumber: 5, name: "G2", note: "G", octave: 2, targetFreq: 98.0 },
    { stringNumber: 4, name: "C3", note: "C", octave: 3, targetFreq: 130.81 },
    { stringNumber: 3, name: "F3", note: "F", octave: 3, targetFreq: 174.61 },
    { stringNumber: 2, name: "A3", note: "A", octave: 3, targetFreq: 220.0 },
    { stringNumber: 1, name: "D4", note: "D", octave: 4, targetFreq: 293.66 },
  ],
  "Standard E (E-A-D-G-B-E)": [
    { stringNumber: 6, name: "E2", note: "E", octave: 2, targetFreq: 82.41 },
    { stringNumber: 5, name: "A2", note: "A", octave: 2, targetFreq: 110.0 },
    { stringNumber: 4, name: "D3", note: "D", octave: 3, targetFreq: 146.83 },
    { stringNumber: 3, name: "G3", note: "G", octave: 3, targetFreq: 196.0 },
    { stringNumber: 2, name: "B3", note: "B", octave: 3, targetFreq: 246.94 },
    { stringNumber: 1, name: "E4", note: "E", octave: 4, targetFreq: 329.63 },
  ],
  "Drop B (B-F#-B-E-G#-C#)": [
    { stringNumber: 6, name: "B1", note: "B", octave: 1, targetFreq: 61.74 },
    { stringNumber: 5, name: "F#2", note: "F#", octave: 2, targetFreq: 92.5 },
    { stringNumber: 4, name: "B2", note: "B", octave: 2, targetFreq: 123.47 },
    { stringNumber: 3, name: "E3", note: "E", octave: 3, targetFreq: 164.81 },
    { stringNumber: 2, name: "G#3", note: "G#", octave: 3, targetFreq: 207.65 },
    { stringNumber: 1, name: "C#4", note: "C#", octave: 4, targetFreq: 277.18 },
  ],
  "Drop A (A-E-A-D-F#-B)": [
    { stringNumber: 6, name: "A1", note: "A", octave: 1, targetFreq: 55.0 },
    { stringNumber: 5, name: "E2", note: "E", octave: 2, targetFreq: 82.41 },
    { stringNumber: 4, name: "A2", note: "A", octave: 2, targetFreq: 110.0 },
    { stringNumber: 3, name: "D3", note: "D", octave: 3, targetFreq: 146.83 },
    { stringNumber: 2, name: "F#3", note: "F#", octave: 3, targetFreq: 185.0 },
    { stringNumber: 1, name: "B3", note: "B", octave: 3, targetFreq: 246.94 },
  ],
};

export const DROP_C_POWER_CHORDS: ChordVoicing[] = [
  {
    chordName: "C5 (Open Chug)",
    metalName: "C5 Heavy Root Barre",
    fretPositions: [0, 0, 0, "x", "x", "x"],
    description: "The cornerstone of Drop C metal. 1-finger open strings (C2-G2-C3) creating massive sub-frequency punch.",
    isBarre: true,
    metalType: "Power Chord",
  },
  {
    chordName: "Db5 / C#5 (Tritone/Phrygian)",
    metalName: "Db5 Half-Step Slam",
    fretPositions: [1, 1, 1, "x", "x", "x"],
    description: "1st fret barre. Pure evil Phrygian dissonance, the signature tritone breakdown note in metalcore.",
    isBarre: true,
    metalType: "Tritone / Diminished",
  },
  {
    chordName: "D5",
    metalName: "D5 Barre Power Chord",
    fretPositions: [2, 2, 2, "x", "x", "x"],
    description: "2nd fret barre. Major second above root, ideal for rapid thrash galloping transitions.",
    isBarre: true,
    metalType: "Power Chord",
  },
  {
    chordName: "Eb5 / D#5",
    metalName: "Eb5 Minor 3rd Chug",
    fretPositions: [3, 3, 3, "x", "x", "x"],
    description: "3rd fret barre. Defines the dark minor tonality of Drop C riffs (August Burns Red, Killswitch Engage).",
    isBarre: true,
    metalType: "Power Chord",
  },
  {
    chordName: "F5",
    metalName: "F5 Perfect 4th Power",
    fretPositions: [5, 5, 5, "x", "x", "x"],
    description: "5th fret barre. Resolves effortlessly back to open C5 with explosive resonance.",
    isBarre: true,
    metalType: "Power Chord",
  },
  {
    chordName: "G5",
    metalName: "G5 Dominant 5th Barre",
    fretPositions: [7, 7, 7, "x", "x", "x"],
    description: "7th fret barre. Perfect fifth harmony, giving colossal stadium metal presence.",
    isBarre: true,
    metalType: "Power Chord",
  },
  {
    chordName: "Ab5 / G#5",
    metalName: "Ab5 Minor 6th Doom/Metalcore",
    fretPositions: [8, 8, 8, "x", "x", "x"],
    description: "8th fret barre. The iconic melodic metalcore chorus root chord (Parkway Drive, Architect).",
    isBarre: true,
    metalType: "Power Chord",
  },
  {
    chordName: "Bb5 / A#5",
    metalName: "Bb5 Minor 7th Anthem",
    fretPositions: [10, 10, 10, "x", "x", "x"],
    description: "10th fret barre. Drives huge uplifting chorus resolutions before hitting the low C5 drop.",
    isBarre: true,
    metalType: "Power Chord",
  },
  {
    chordName: "C Add9 (Metalcore Shape)",
    metalName: "C Add9 Dissonant Ring",
    fretPositions: [0, 0, 0, 2, 3, "x"],
    description: "Open C-G-C barre with high 2nd & 3rd frets ringing out. Adam D (Killswitch) signature chord.",
    isBarre: false,
    metalType: "Add9 / Metalcore",
  },
  {
    chordName: "Ab Add9 (Epic Chorus)",
    metalName: "Ab Add9 Huge Voicing",
    fretPositions: [8, 8, 8, 10, 12, "x"],
    description: "Huge stretched metalcore chord that fills the stereo field with lush harmonic sustain.",
    isBarre: false,
    metalType: "Add9 / Metalcore",
  },
  {
    chordName: "Djent Diminished 5th",
    metalName: "Meshuggah Low Clamp",
    fretPositions: [0, 1, "x", "x", "x", "x"],
    description: "Dissonant low interval clamped against the open low C for syncopated rhythmic breakdowns.",
    isBarre: false,
    metalType: "Djent Inversion",
  },
  {
    chordName: "C Minor (Full Metal Resonance)",
    metalName: "C Minor High String Bloom",
    fretPositions: [0, 0, 0, 5, 6, 8],
    description: "Full 6-string Drop C minor chord. Low crushing bottom coupled with crying high triadic notes.",
    isBarre: false,
    metalType: "Open Resonant",
  },
];

export const POPULAR_SONG_PRESETS = [
  {
    title: "Smells Like Teen Spirit",
    artist: "Nirvana",
    originalKey: "F Minor",
    metalSubgenre: "Metalcore",
    inputChords: "F5 - Bb5 - Ab5 - Db5 (Original 4-chord grunge loop)",
    description: "Re-engineered in Drop C into 16th-note palm-muted chugs, Add9 wide chorus chords, and heavy half-time breakdown.",
    previewBpm: 120,
  },
  {
    title: "Sweet Child O' Mine",
    artist: "Guns N' Roses",
    originalKey: "Db / D Major",
    metalSubgenre: "Modern Metalcore / Drop C",
    inputChords: "D - C - G - D (Iconic stadium intro & verse)",
    description: "Transposed down to Drop C with crushing 0-0-0 chugs, sweeping arpeggio harmonizations, and blast-beat transition.",
    previewBpm: 135,
  },
  {
    title: "Hotel California",
    artist: "Eagles",
    originalKey: "B Minor",
    metalSubgenre: "Doom / Sludge",
    inputChords: "Bm - F# - A - E - G - D - Em - F#",
    description: "Transformed into dark C-Phrygian doom metal with cavernous reverb and thick sludgy power chords.",
    previewBpm: 75,
  },
  {
    title: "Shape of You",
    artist: "Ed Sheeran",
    originalKey: "C# Minor",
    metalSubgenre: "Djent / Progressive",
    inputChords: "C#m - F#m - A - B (Pop progression)",
    description: "Converted to syncopated 7/8 djent chugs with tight gate clamping, pitch squeals, and heavy 0-0-0 drops.",
    previewBpm: 128,
  },
  {
    title: "Creep",
    artist: "Radiohead",
    originalKey: "G Major",
    metalSubgenre: "Swedish Death Metal",
    inputChords: "G - B - C - Cm",
    description: "Stockholm HM-2 chainsaw distortion makeover with tremolo picking and Gothenburg dual melodic lines.",
    previewBpm: 110,
  },
  {
    title: "Wonderwall",
    artist: "Oasis",
    originalKey: "F# Minor",
    metalSubgenre: "80s Thrash Metal",
    inputChords: "Em7 - G - Dsus4 - A7sus4",
    description: "Turned into high-velocity 180 BPM downpicked Bay Area thrash gallop with screaming whammy leads.",
    previewBpm: 175,
  },
];

export const METAL_SCALES = [
  {
    name: "C Phrygian Dominant (Metal Favorite)",
    formula: "1 - b2 - 3 - 4 - 5 - b6 - b7",
    notes: ["C", "Db", "E", "F", "G", "Ab", "Bb"],
    vibe: "Dark, exotic, Middle Eastern, Egyptian, Thrash/Death metal signature (Slayer, Nile, Lamb of God).",
  },
  {
    name: "C Harmonic Minor",
    formula: "1 - 2 - b3 - 4 - 5 - b6 - 7",
    notes: ["C", "D", "Eb", "F", "G", "Ab", "B"],
    vibe: "Neoclassical shred, dramatic tension, Yngwie / Children of Bodom leads.",
  },
  {
    name: "C Natural Minor (Aeolian)",
    formula: "1 - 2 - b3 - 4 - 5 - b6 - b7",
    notes: ["C", "D", "Eb", "F", "G", "Ab", "Bb"],
    vibe: "Melodic metalcore, Iron Maiden gallops, Parkway Drive choruses.",
  },
  {
    name: "C Minor Pentatonic + Blues Note",
    formula: "1 - b3 - 4 - b5 - 5 - b7",
    notes: ["C", "Eb", "F", "F#", "G", "Bb"],
    vibe: "Raw Pantera groove metal, Black Sabbath sludge riffs, pinch harmonic heaven.",
  },
  {
    name: "C Locrian (Maximum Dissonance)",
    formula: "1 - b2 - b3 - 4 - b5 - b6 - b7",
    notes: ["C", "Db", "Eb", "F", "Gb", "Ab", "Bb"],
    vibe: "Extreme death metal, technical djent dissonance, diminished 5th dread.",
  },
];
