import { AmpPreset } from "../types";

export const FACTORY_PRESETS: AmpPreset[] = [
  {
    id: "preset-5150-chug",
    name: "5150 Modern Metalcore Chug",
    subgenre: "Metalcore",
    description: "Classic high-gain punch with tight TS9 bass cut, focused mids, and fast noise gate for punishing 0-0-0 palm mutes.",
    iconName: "Flame",
    params: {
      gateEnabled: true,
      gateThreshold: -50,
      gateRelease: 0.04,
      driveEnabled: true,
      driveGain: 2.2,
      driveTone: 7.0,
      driveLevel: 8.5,
      driveMidBoost: true,
      ampModel: "5150 High-Gain",
      gain: 7.8,
      bass: 5.5,
      middle: 6.8,
      treble: 7.2,
      presence: 7.5,
      resonance: 6.8,
      master: 6.5,
      cabModel: "Mesa OS 4x12 V30",
      micType: "Shure SM57 Dynamic",
      micPlacement: "Cap-Edge",
      cabAir: 4.0,
      eqEnabled: true,
      eq80Hz: -2.0,
      eq250Hz: -1.0,
      eq750Hz: 2.5,
      eq2200Hz: 3.0,
      eq6000Hz: 1.5,
      chorusEnabled: false,
      chorusRate: 1.0,
      chorusDepth: 2.0,
      chorusMix: 0,
      delayEnabled: false,
      delayTime: 380,
      delayFeedback: 3.5,
      delayMix: 2.0,
      delayPingPong: false,
      reverbEnabled: true,
      reverbType: "Dark Room",
      reverbDecay: 1.2,
      reverbMix: 1.8,
    },
  },
  {
    id: "preset-mesa-nu-metal",
    name: "Mesa Dual Rectifier Nu-Metal",
    subgenre: "Nu-Metal",
    description: "Massive wall of sub-bass low end, scooped upper mids, and aggressive presence (Deftones, Slipknot Drop C era).",
    iconName: "Skull",
    params: {
      gateEnabled: true,
      gateThreshold: -46,
      gateRelease: 0.08,
      driveEnabled: false,
      driveGain: 0,
      driveTone: 5.0,
      driveLevel: 7.0,
      driveMidBoost: false,
      ampModel: "Mesa Dual Rectifier",
      gain: 8.5,
      bass: 8.2,
      middle: 3.8,
      treble: 7.8,
      presence: 8.0,
      resonance: 8.5,
      master: 7.0,
      cabModel: "Mesa OS 4x12 V30",
      micType: "Royer R-121 Ribbon",
      micPlacement: "Center",
      cabAir: 5.5,
      eqEnabled: true,
      eq80Hz: 3.5,
      eq250Hz: 1.0,
      eq750Hz: -4.0,
      eq2200Hz: 2.5,
      eq6000Hz: 3.0,
      chorusEnabled: false,
      chorusRate: 0.8,
      chorusDepth: 3.0,
      chorusMix: 0,
      delayEnabled: false,
      delayTime: 420,
      delayFeedback: 4.0,
      delayMix: 0,
      reverbEnabled: true,
      reverbType: "Catacomb Hall",
      reverbDecay: 2.0,
      reverbMix: 2.5,
    },
  },
  {
    id: "preset-djent-808",
    name: "Djent 808 Laser Precision",
    subgenre: "Djent",
    description: "Ultra-fast clamp noise gate, aggressive 1.5kHz mid clank, and razor-sharp low-end roll off for intricate polyrhythms.",
    iconName: "Zap",
    params: {
      gateEnabled: true,
      gateThreshold: -42,
      gateRelease: 0.02,
      driveEnabled: true,
      driveGain: 1.5,
      driveTone: 8.5,
      driveLevel: 9.5,
      driveMidBoost: true,
      ampModel: "Diezel VH4",
      gain: 7.0,
      bass: 4.2,
      middle: 8.0,
      treble: 7.5,
      presence: 8.5,
      resonance: 5.0,
      master: 7.2,
      cabModel: "ENGL Pro V30",
      micType: "Shure SM57 Dynamic",
      micPlacement: "Cap-Edge",
      cabAir: 3.0,
      eqEnabled: true,
      eq80Hz: -5.0,
      eq250Hz: 0,
      eq750Hz: 4.0,
      eq2200Hz: 4.5,
      eq6000Hz: 2.0,
      chorusEnabled: false,
      chorusRate: 1.2,
      chorusDepth: 1.5,
      chorusMix: 0,
      delayEnabled: false,
      delayTime: 300,
      delayFeedback: 2.0,
      delayMix: 0,
      reverbEnabled: false,
      reverbType: "Dark Room",
      reverbDecay: 0.8,
      reverbMix: 0,
    },
  },
  {
    id: "preset-hm2-chainsaw",
    name: "Swedish Death HM-2 Buzzsaw",
    subgenre: "Swedish Death Metal",
    description: "All dials dimed on the legendary Japanese HM-2 pedal through a roaring British stack. Pure grinding Stockholm buzzsaw tone.",
    iconName: "Crosshair",
    params: {
      gateEnabled: true,
      gateThreshold: -48,
      gateRelease: 0.06,
      driveEnabled: true,
      driveGain: 9.0,
      driveTone: 9.5,
      driveLevel: 8.0,
      driveMidBoost: true,
      ampModel: "HM-2 Chainsaw",
      gain: 9.2,
      bass: 9.0,
      middle: 9.5,
      treble: 9.0,
      presence: 8.0,
      resonance: 7.5,
      master: 6.8,
      cabModel: "Marshall 1960A Greenback",
      micType: "Shure SM57 Dynamic",
      micPlacement: "Cone",
      cabAir: 6.0,
      eqEnabled: true,
      eq80Hz: 2.0,
      eq250Hz: 3.0,
      eq750Hz: 5.0,
      eq2200Hz: 4.0,
      eq6000Hz: 2.0,
      chorusEnabled: false,
      chorusRate: 0.5,
      chorusDepth: 1.0,
      chorusMix: 0,
      delayEnabled: false,
      delayTime: 350,
      delayFeedback: 2.0,
      delayMix: 0,
      reverbEnabled: true,
      reverbType: "Catacomb Hall",
      reverbDecay: 2.5,
      reverbMix: 2.0,
    },
  },
  {
    id: "preset-80s-thrash",
    name: "80s Bay Area Thrash Master",
    subgenre: "Thrash Metal",
    description: "Scooped mid crunch, bitey high treble, and blistering palm-mute response for lightning-fast downpicking.",
    iconName: "ShieldAlert",
    params: {
      gateEnabled: true,
      gateThreshold: -54,
      gateRelease: 0.05,
      driveEnabled: true,
      driveGain: 3.0,
      driveTone: 7.5,
      driveLevel: 7.5,
      driveMidBoost: false,
      ampModel: "Marshall JCM800",
      gain: 8.5,
      bass: 6.5,
      middle: 4.0,
      treble: 8.5,
      presence: 8.5,
      resonance: 6.0,
      master: 7.5,
      cabModel: "Marshall 1960A Greenback",
      micType: "Shure SM57 Dynamic",
      micPlacement: "Center",
      cabAir: 4.5,
      eqEnabled: true,
      eq80Hz: 1.0,
      eq250Hz: -2.0,
      eq750Hz: -3.5,
      eq2200Hz: 3.5,
      eq6000Hz: 4.0,
      chorusEnabled: false,
      chorusRate: 1.0,
      chorusDepth: 2.0,
      chorusMix: 0,
      delayEnabled: false,
      delayTime: 320,
      delayFeedback: 2.5,
      delayMix: 0,
      reverbEnabled: true,
      reverbType: "Dark Room",
      reverbDecay: 1.0,
      reverbMix: 1.5,
    },
  },
  {
    id: "preset-doom-sludge",
    name: "Sludge & Doom Wall of Fuzz",
    subgenre: "Doom / Sludge",
    description: "Thick, earth-shaking low octave fuzz with massive poweramp sag and cavernous reverb. Built for crushing, slow Drop C riffs.",
    iconName: "Volume2",
    params: {
      gateEnabled: false,
      gateThreshold: -70,
      gateRelease: 0.2,
      driveEnabled: true,
      driveGain: 8.5,
      driveTone: 4.0,
      driveLevel: 9.0,
      driveMidBoost: false,
      ampModel: "ENGL Savage",
      gain: 9.0,
      bass: 9.5,
      middle: 5.5,
      treble: 5.0,
      presence: 4.5,
      resonance: 9.5,
      master: 8.5,
      cabModel: "Orange PPC412",
      micType: "Royer R-121 Ribbon",
      micPlacement: "Cone",
      cabAir: 8.0,
      eqEnabled: true,
      eq80Hz: 6.0,
      eq250Hz: 3.5,
      eq750Hz: 1.0,
      eq2200Hz: -2.0,
      eq6000Hz: -3.0,
      chorusEnabled: false,
      chorusRate: 0.4,
      chorusDepth: 4.0,
      chorusMix: 0,
      delayEnabled: false,
      delayTime: 500,
      delayFeedback: 5.0,
      delayMix: 0,
      reverbEnabled: true,
      reverbType: "Catacomb Hall",
      reverbDecay: 4.5,
      reverbMix: 5.0,
    },
  },
  {
    id: "preset-prog-liquid-lead",
    name: "Prog Metal Liquid Lead",
    subgenre: "Prog Metal",
    description: "Silky smooth sustain, rich harmonic overtones, ping-pong stereo delay, and stereo chorus for expressive guitar solos.",
    iconName: "Music",
    params: {
      gateEnabled: true,
      gateThreshold: -58,
      gateRelease: 0.12,
      driveEnabled: true,
      driveGain: 3.5,
      driveTone: 6.5,
      driveLevel: 8.0,
      driveMidBoost: true,
      ampModel: "5150 High-Gain",
      gain: 8.2,
      bass: 5.8,
      middle: 7.5,
      treble: 6.8,
      presence: 6.5,
      resonance: 6.0,
      master: 7.0,
      cabModel: "Mesa OS 4x12 V30",
      micType: "Shure SM57 Dynamic",
      micPlacement: "Cap-Edge",
      cabAir: 5.0,
      eqEnabled: true,
      eq80Hz: -1.0,
      eq250Hz: 1.0,
      eq750Hz: 3.0,
      eq2200Hz: 2.0,
      eq6000Hz: 1.0,
      chorusEnabled: true,
      chorusRate: 1.4,
      chorusDepth: 3.5,
      chorusMix: 3.5,
      delayEnabled: true,
      delayTime: 440,
      delayFeedback: 5.5,
      delayMix: 4.5,
      delayPingPong: true,
      reverbEnabled: true,
      reverbType: "Plate Metal",
      reverbDecay: 3.0,
      reverbMix: 4.0,
    },
  },
  {
    id: "preset-clean-ambient-shimmer",
    name: "Clean Ambient Shimmer (Deftones/Gojira)",
    subgenre: "Prog Metal",
    description: "Pristine, sparkling clean tone with lush stereo modulation and cathedral reverb for intro arpeggios and atmospheric breakdowns.",
    iconName: "Sparkles",
    params: {
      gateEnabled: true,
      gateThreshold: -65,
      gateRelease: 0.1,
      driveEnabled: false,
      driveGain: 0,
      driveTone: 5.0,
      driveLevel: 5.0,
      driveMidBoost: false,
      ampModel: "Marshall JCM800",
      gain: 2.5,
      bass: 6.0,
      middle: 6.5,
      treble: 7.8,
      presence: 8.0,
      resonance: 5.5,
      master: 8.0,
      cabModel: "ENGL Pro V30",
      micType: "Royer R-121 Ribbon",
      micPlacement: "Center",
      cabAir: 7.0,
      eqEnabled: true,
      eq80Hz: 1.0,
      eq250Hz: 0.5,
      eq750Hz: 1.0,
      eq2200Hz: 3.0,
      eq6000Hz: 4.5,
      chorusEnabled: true,
      chorusRate: 1.8,
      chorusDepth: 6.0,
      chorusMix: 6.5,
      delayEnabled: true,
      delayTime: 480,
      delayFeedback: 6.0,
      delayMix: 5.0,
      delayPingPong: true,
      reverbEnabled: true,
      reverbType: "Shimmer Ambient",
      reverbDecay: 5.5,
      reverbMix: 6.5,
    },
  },
];
